/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QaFootRouteImport } from './routes/qa-foot'
import { Route as PrototypeRouteImport } from './routes/prototype'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVisitRouteImport } from './routes/app.visit'
import { Route as AppUpcomingRouteImport } from './routes/app.upcoming'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppSoapRouteImport } from './routes/app.soap'
import { Route as AppPatientsRouteImport } from './routes/app.patients'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppIncomeRouteImport } from './routes/app.income'
import { Route as AppDictationUsageRouteImport } from './routes/app.dictation-usage'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppAssessRouteImport } from './routes/app.assess'
import { Route as AppPatientsNewRouteImport } from './routes/app.patients_.new'
import { Route as AppPatientsIdRouteImport } from './routes/app.patients_.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QaFootRoute = QaFootRouteImport.update({
  id: '/qa-foot',
  path: '/qa-foot',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeRoute = PrototypeRouteImport.update({
  id: '/prototype',
  path: '/prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVisitRoute = AppVisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => AppRoute,
} as any)
const AppUpcomingRoute = AppUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSoapRoute = AppSoapRouteImport.update({
  id: '/soap',
  path: '/soap',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppDictationUsageRoute = AppDictationUsageRouteImport.update({
  id: '/dictation-usage',
  path: '/dictation-usage',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessRoute = AppAssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsNewRoute = AppPatientsNewRouteImport.update({
  id: '/patients_/new',
  path: '/patients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIdRoute = AppPatientsIdRouteImport.update({
  id: '/patients_/$id',
  path: '/patients/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/prototype': typeof PrototypeRoute
  '/qa-foot': typeof QaFootRoute
  '/signup': typeof SignupRoute
  '/app/assess': typeof AppAssessRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dictation-usage': typeof AppDictationUsageRoute
  '/app/income': typeof AppIncomeRoute
  '/app/notes': typeof AppNotesRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/soap': typeof AppSoapRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/upcoming': typeof AppUpcomingRoute
  '/app/visit': typeof AppVisitRoute
  '/app/patients/$id': typeof AppPatientsIdRoute
  '/app/patients/new': typeof AppPatientsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/prototype': typeof PrototypeRoute
  '/qa-foot': typeof QaFootRoute
  '/signup': typeof SignupRoute
  '/app/assess': typeof AppAssessRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dictation-usage': typeof AppDictationUsageRoute
  '/app/income': typeof AppIncomeRoute
  '/app/notes': typeof AppNotesRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/soap': typeof AppSoapRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/upcoming': typeof AppUpcomingRoute
  '/app/visit': typeof AppVisitRoute
  '/app/patients/$id': typeof AppPatientsIdRoute
  '/app/patients/new': typeof AppPatientsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/prototype': typeof PrototypeRoute
  '/qa-foot': typeof QaFootRoute
  '/signup': typeof SignupRoute
  '/app/assess': typeof AppAssessRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/dictation-usage': typeof AppDictationUsageRoute
  '/app/income': typeof AppIncomeRoute
  '/app/notes': typeof AppNotesRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/soap': typeof AppSoapRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/upcoming': typeof AppUpcomingRoute
  '/app/visit': typeof AppVisitRoute
  '/app/patients_/$id': typeof AppPatientsIdRoute
  '/app/patients_/new': typeof AppPatientsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/prototype'
    | '/qa-foot'
    | '/signup'
    | '/app/assess'
    | '/app/assistant'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/dictation-usage'
    | '/app/income'
    | '/app/notes'
    | '/app/patients'
    | '/app/soap'
    | '/app/subscription'
    | '/app/upcoming'
    | '/app/visit'
    | '/app/patients/$id'
    | '/app/patients/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/prototype'
    | '/qa-foot'
    | '/signup'
    | '/app/assess'
    | '/app/assistant'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/dictation-usage'
    | '/app/income'
    | '/app/notes'
    | '/app/patients'
    | '/app/soap'
    | '/app/subscription'
    | '/app/upcoming'
    | '/app/visit'
    | '/app/patients/$id'
    | '/app/patients/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/prototype'
    | '/qa-foot'
    | '/signup'
    | '/app/assess'
    | '/app/assistant'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/dictation-usage'
    | '/app/income'
    | '/app/notes'
    | '/app/patients'
    | '/app/soap'
    | '/app/subscription'
    | '/app/upcoming'
    | '/app/visit'
    | '/app/patients_/$id'
    | '/app/patients_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrototypeRoute: typeof PrototypeRoute
  QaFootRoute: typeof QaFootRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-foot': {
      id: '/qa-foot'
      path: '/qa-foot'
      fullPath: '/qa-foot'
      preLoaderRoute: typeof QaFootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype': {
      id: '/prototype'
      path: '/prototype'
      fullPath: '/prototype'
      preLoaderRoute: typeof PrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/visit': {
      id: '/app/visit'
      path: '/visit'
      fullPath: '/app/visit'
      preLoaderRoute: typeof AppVisitRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upcoming': {
      id: '/app/upcoming'
      path: '/upcoming'
      fullPath: '/app/upcoming'
      preLoaderRoute: typeof AppUpcomingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/soap': {
      id: '/app/soap'
      path: '/soap'
      fullPath: '/app/soap'
      preLoaderRoute: typeof AppSoapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/income': {
      id: '/app/income'
      path: '/income'
      fullPath: '/app/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dictation-usage': {
      id: '/app/dictation-usage'
      path: '/dictation-usage'
      fullPath: '/app/dictation-usage'
      preLoaderRoute: typeof AppDictationUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assess': {
      id: '/app/assess'
      path: '/assess'
      fullPath: '/app/assess'
      preLoaderRoute: typeof AppAssessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients_/new': {
      id: '/app/patients_/new'
      path: '/patients/new'
      fullPath: '/app/patients/new'
      preLoaderRoute: typeof AppPatientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients_/$id': {
      id: '/app/patients_/$id'
      path: '/patients/$id'
      fullPath: '/app/patients/$id'
      preLoaderRoute: typeof AppPatientsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssessRoute: typeof AppAssessRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDictationUsageRoute: typeof AppDictationUsageRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppSoapRoute: typeof AppSoapRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppUpcomingRoute: typeof AppUpcomingRoute
  AppVisitRoute: typeof AppVisitRoute
  AppPatientsIdRoute: typeof AppPatientsIdRoute
  AppPatientsNewRoute: typeof AppPatientsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssessRoute: AppAssessRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDictationUsageRoute: AppDictationUsageRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppNotesRoute: AppNotesRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppSoapRoute: AppSoapRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppUpcomingRoute: AppUpcomingRoute,
  AppVisitRoute: AppVisitRoute,
  AppPatientsIdRoute: AppPatientsIdRoute,
  AppPatientsNewRoute: AppPatientsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrototypeRoute: PrototypeRoute,
  QaFootRoute: QaFootRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
